// config.bin - 17:22:13 04/24/15, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	 //  = 2,	// Error parsing: Empty enum name
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXESXYZ = 4,
	STABILIZEDINAXISY = 2,
	STABILIZEDINAXESBOTH = 3,
	DESTRUCTNO = 0,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class DefaultEventhandlers;	// External class reference

class CfgPatches {
	class PG_Services_PMC_Gear {
		units[] = {};
		weapons[] = {"arifle_MX_blk_F", "arifle_MX_GL_blk_F", "arifle_MX_MRCO_blk_F", "arifle_MX_GL_blk_ACO_F", "V_PlateCarrierInd_PMC_blk", "V_PlateCarrierInd_PMC_grn", "V_TacVest_darkblck", "V_PlateCarrier1_PMC_khki", "V_PlateCarrier1_PMC_marpat", "V_PlateCarrier1_PMC_rgr", "V_PlateCarrier1_PMC_blk", "V_PlateCarrier1_PMC_coyote", "pmc_earpiece", "H_Cap_pmc_headphones", "H_Cap_pmc", "H_Cap_tan_pmc", "H_Capbw_pmc", "H_Capbw_tan_pmc", "H_HelmetB_plain_blk", "H_PilotHelmetHeli_PMC", "H_Booniehat_rgr", "H_Booniehat_GCAMO", "H_Booniehat_DMARPAT"};
		requiredVersion = 0.1;
		requiredAddons[] = {};
		version = 0.1;
	};
};

class UniformSlotInfo {
	slotType = 0;
	linkProxy = "-";
};

class cfgWeapons {
	class arifle_MX_Black_F;	// External class reference
	class arifle_MX_GL_Black_F;	// External class reference
	class ItemCore;	// External class reference
	class VestItem;	// External class reference
	class NVGoggles;	// External class reference
	class Vest_NoCamo_Base;	// External class reference
	class V_TacVestIR_blk;	// External class reference
	class V_PlateCarrierIA1_dgtl;	// External class reference
	class V_PlateCarrier1_rgr;	// External class reference
	class V_TacVest_khk;	// External class reference
	class HeadgearItem;	// External class reference
	class H_Cap_red;	// External class reference
	class H_Booniehat_khk;	// External class reference
	
	class arifle_MX_blk_F : arifle_MX_Black_F {
		scope = 2;
		author = "BadHabitz";
		displayName = "(PG) MX 6.5 mm (Black)";
		hiddenSelections[] = {"camo1", "camo2"};
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\Textures\Weapons\xmx_basebk_co.paa", "\PG_Services_PMC\Textures\Weapons\xmx_shortbk_co.paa"};
	};
	
	class arifle_MX_GL_blk_F : arifle_MX_GL_Black_F {
		scope = 2;
		author = "BadHabitz";
		displayName = "(PG) MX 3GL 6.5 mm (Black)";
		hiddenSelections[] = {"camo1", "camo2"};
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\Textures\Weapons\xmx_basebk_co.paa", "\PG_Services_PMC\Textures\Weapons\glxbk_co.paa"};
	};
	
	class arifle_MX_MRCO_blk_F : arifle_MX_Black_F {
		scope = 1;
		author = "Pomigit";
		displayName = "(PG) MX 6.5 mm (Black)";
		hiddenSelections[] = {"camo1", "camo2"};
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\Textures\Weapons\xmx_basebk_co.paa", "\PG_Services_PMC\Textures\Weapons\xmx_shortbk_co.paa"};
		
		class LinkedItems {
			class LinkedItemsOptic {
				slot = "CowsSlot";
				item = "optic_MRCO";
			};
		};
	};
	
	class arifle_MX_GL_blk_ACO_F : arifle_MX_GL_Black_F {
		scope = 1;
		author = "Pomigit";
		displayName = "(PG) MX 3GL 6.5 mm (Black)";
		hiddenSelections[] = {"camo1", "camo2"};
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\Textures\Weapons\xmx_basebk_co.paa", "\PG_Services_PMC\Textures\Weapons\glxbk_co.paa"};
		
		class LinkedItems {
			class LinkedItemsOptic {
				slot = "CowsSlot";
				item = "optic_ACO";
			};
		};
	};
	
	class V_PlateCarrierInd_PMC_blk : V_PlateCarrierIA1_dgtl {
		scope = 2;
		author = "Pomigit";
		displayName = "(PG) Black Full Plate Carrier";
		picture = "\PG_Services_PMC\icons\icon_V_PlateCarrierInd_PMC_blk.paa";
		model = "A3\Characters_F_Beta\INDEP\equip_ia_vest02";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Vests\equip_vest02_in_pmc_blk_co.paa"};
		
		class ItemInfo : VestItem {
			containerClass = "Supply140";
			uniformModel = "A3\Characters_F_Beta\INDEP\equip_ia_vest02";
			hiddenSelections[] = {"camo"};
			passThrough = 0.5;
			armor = 110;
			mass = 110;
		};
	};
	
	class V_PlateCarrierInd_PMC_grn : V_PlateCarrierIA1_dgtl {
		scope = 2;
		author = "Pomigit";
		displayName = "(PG) Green Full Plate Carrier";
		picture = "\PG_Services_PMC\icons\icon_V_PlateCarrierInd_PMC_grn.paa";
		Model = "A3\Characters_F_Beta\INDEP\equip_ia_vest02";
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Vests\equip_vest02_in_pmc_grn_co.paa"};
		hiddenSelections[] = {"camo"};
		
		class ItemInfo : VestItem {
			uniformModel = "A3\Characters_F_Beta\INDEP\equip_ia_vest02";
			containerClass = "Supply140";
			hiddenSelections[] = {"camo"};
			passThrough = 0.5;
			armor = 110;
			mass = 110;
		};
	};
	
	class V_TacVest_darkblck : V_TacVest_khk {
		scope = 2;
		author = "Pomigit";
		displayName = "(PG) Tactical Vest (black)";
		picture = "\A3\characters_f\Data\UI\icon_v_tacvest_blk_ca.paa";
		model = "A3\Characters_F\Common\equip_tacticalvest";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Vests\tacticalvest_darkblack_co.paa"};
		
		class ItemInfo : VestItem {
			uniformModel = "A3\Characters_F\Common\equip_tacticalvest";
			containerClass = "Supply140";
			passThrough = 1;
			armor = 20;
			mass = 40;
		};
	};
	
	class V_PlateCarrier1_PMC_khki : V_PlateCarrier1_rgr {
		scope = 2;
		author = "Pomigit";
		displayName = "(PG) Khaki Plate Carrier";
		picture = "\PG_Services_PMC\icons\icon_V_PlateCarrier1_PMC_khki.paa";
		model = "\A3\Characters_F\BLUFOR\equip_b_vest02";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Vests\vests_pmc_khki_co.paa"};
		
		class ItemInfo : VestItem {
			uniformModel = "\A3\Characters_F\BLUFOR\equip_b_vest02";
			hiddenSelections[] = {"camo"};
			containerClass = "Supply140";
			passThrough = 0.5;
			armor = 100;
			mass = 100;
		};
	};
	
	class V_PlateCarrier1_PMC_marpat : V_PlateCarrier1_rgr {
		scope = 2;
		author = "Pomigit";
		displayName = "(PG) MARPAT Plate Carrier";
		picture = "\PG_Services_PMC\icons\icon_V_PlateCarrier1_PMC_marpat.paa";
		model = "\A3\Characters_F\BLUFOR\equip_b_vest02";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Vests\vests_pmc_marpat_co.paa"};
		
		class ItemInfo : VestItem {
			uniformModel = "\A3\Characters_F\BLUFOR\equip_b_vest02";
			hiddenSelections[] = {"camo"};
			containerClass = "Supply140";
			passThrough = 0.5;
			armor = 100;
			mass = 100;
		};
	};
	
	class V_PlateCarrier1_PMC_rgr : V_PlateCarrier1_rgr {
		scope = 2;
		author = "Pomigit";
		displayName = "(PG) Green Plate Carrier";
		picture = "\PG_Services_PMC\icons\icon_V_PlateCarrier1_PMC_rgr.paa";
		model = "\A3\Characters_F\BLUFOR\equip_b_vest02";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Vests\vests_PG_rgr_co.paa"};
		
		class ItemInfo : VestItem {
			uniformModel = "\A3\Characters_F\BLUFOR\equip_b_vest02";
			hiddenSelections[] = {"camo"};
			containerClass = "Supply140";
			passThrough = 0.5;
			armor = 100;
			mass = 100;
		};
	};
	
	class V_PlateCarrier1_PMC_blk : V_PlateCarrier1_rgr {
		scope = 2;
		author = "Pomigit";
		displayName = "(PG) Black Plate Carrier";
		picture = "\PG_Services_PMC\icons\icon_V_PlateCarrier1_PMC_blk.paa";
		model = "\A3\Characters_F\BLUFOR\equip_b_vest02";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Vests\vests_PG_blk_co.paa"};
		
		class ItemInfo : VestItem {
			uniformModel = "\A3\Characters_F\BLUFOR\equip_b_vest02";
			hiddenSelections[] = {"camo"};
			containerClass = "Supply140";
			passThrough = 0.5;
			armor = 100;
			mass = 100;
		};
	};
	
	class V_PlateCarrier1_PMC_coyote : V_PlateCarrier1_rgr {
		scope = 2;
		author = "BadHabitz";
		displayName = "(PG) Coyote Plate Carrier";
		picture = "\PG_Services_PMC\icons\icon_V_PlateCarrier1_PMC_khki.paa";
		model = "\A3\Characters_F\BLUFOR\equip_b_vest02";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Vests\vests_PG_tan_co.paa"};
		
		class ItemInfo : VestItem {
			uniformModel = "\A3\Characters_F\BLUFOR\equip_b_vest02";
			hiddenSelections[] = {"camo"};
			containerClass = "Supply140";
			passThrough = 0.5;
			armor = 100;
			mass = 100;
		};
	};
	
	class pmc_earpiece : NVGoggles {
		author = "Pomigit";
		displayName = "(PG) Radio Earpiece";
		picture = "\PG_Services_PMC\icons\icon_H_earpiece.paa";
		model = "\PG_Services_PMC\earpiece.p3d";
		modelOptics = "-";
		
		class ItemInfo {
			type = 616;
			hmdType = 0;
			uniformModel = "\PG_Services_PMC\earpiece.p3d";
			modelOff = "\PG_Services_PMC\earpiece.p3d";
			mass = 4;
		};
	};
	
	class H_Cap_pmc_headphones : ItemCore {
		scope = 2;
		author = "Pomigit";
		displayName = "(PG) Team Leader Cap";
		picture = "\PG_Services_PMC\icons\icon_H_Cap_pmc_headphones.paa";
		model = "\A3\Characters_F\common\capb_headphones.p3d";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Headgear\capb_headphones_pmc_co.paa"};
		
		class ItemInfo : HeadgearItem {
			mass = 3;
			uniformModel = "\A3\Characters_F\common\capb_headphones.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"camo"};
			allowedSlots[] = {801, 901, 701, 605};
			armor = 3*0.05;
			passThrough = 0.95;
		};
	};
	
	class H_Cap_pmc : H_Cap_red {
		author = "Pomigit";
		displayName = "(PG) Black Logo ballcap";
		picture = "\PG_Services_PMC\icons\icon_H_Cap_pmc.paa";
		model = "\A3\Characters_F\common\capb";
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Headgear\capb_pmc.paa"};
		
		class ItemInfo : HeadgearItem {
			mass = 3;
			uniformModel = "\A3\Characters_F\common\capb.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"camo"};
			allowedSlots[] = {801, 901, 701, 605};
			armor = 3*0.05;
			passThrough = 0.95;
		};
	};
	
	class H_Cap_tan_pmc : H_Cap_pmc {
		author = "Pomigit";
		displayName = "(PG) Tan Logo Ballcap";
		picture = "\PG_Services_PMC\icons\icon_H_Cap_tan_pmc.paa";
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Headgear\capb_tan_pmc.paa"};
	};
	
	class H_Capbw_pmc : ItemCore {
		author = "Pomigit";
		scope = 2;
		weaponPoolAvailable = 1;
		displayName = "(PG) Black Logo ballcap";
		picture = "\PG_Services_PMC\icons\icon_H_Capbw_pmc.paa";
		model = "\PG_Services_PMC\capb_backwards.p3d";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Headgear\capb_pmc.paa"};
		
		class ItemInfo : HeadgearItem {
			mass = 2;
			uniformModel = "\PG_Services_PMC\capb_backwards.p3d";
			modelSides[] = {3, 1};
			armor = 3*0.5;
			passThrough = 0.1;
			hiddenSelections[] = {"camo"};
		};
	};
	
	class H_Capbw_tan_pmc : H_Capbw_pmc {
		author = "Pomigit";
		displayName = "(PG) Tan Logo Ballcap";
		picture = "\PG_Services_PMC\icons\icon_H_Capbw_tan_pmc.paa";
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Headgear\capb_tan_pmc.paa"};
	};
	
	class H_HelmetB_plain_blk : ItemCore {
		author = "Pomigit";
		scope = 2;
		weaponPoolAvailable = 1;
		displayName = "(PG) Black Balistic Helmet";
		picture = "\PG_Services_PMC\icons\icon_H_HelmetB_plain_blk.paa";
		model = "\A3\characters_f\blufor\headgear_b_helmet_plain";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Headgear\equip1_blck_co.paa"};
		
		class ItemInfo : HeadgearItem {
			mass = 100;
			uniformModel = "\A3\characters_f\blufor\headgear_b_helmet_plain";
			hiddenSelections[] = {"camo"};
			modelSides[] = {3, 1};
			armor = 3*0.5;
			passThrough = 0.8;
		};
	};
	
	class H_PilotHelmetHeli_PMC : ItemCore {
		author = "Pomigit";
		scope = 2;
		weaponPoolAvailable = 1;
		displayName = "(PG) Heli Pilot Helmet (Tan)";
		picture = "\PG_Services_PMC\icons\icon_H_PilotHelmetHeli_PMC.paa";
		model = "A3\Characters_F\Common\headgear_helmet_heli";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Headgear\helmet_heli_pmc.paa"};
		
		class ItemInfo : HeadgearItem {
			mass = 120;
			uniformModel = "A3\Characters_F\Common\headgear_helmet_heli";
			modelSides[] = {3, 1};
			armor = 3*0.3;
			passThrough = 0.9;
			hiddenSelections[] = {"camo"};
		};
	};
	
	class H_Booniehat_rgr : H_Booniehat_khk {
		author = "Pomigit";
		displayName = "(PG) Boonie Hat (Ranger Green)";
		picture = "\PG_Services_PMC\icons\icon_H_Booniehat_rgr.paa";
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Headgear\booniehat_rgr_co.paa"};
	};
	
	class H_Booniehat_DMARPAT : H_Booniehat_khk {
		author = "Pomigit";
		displayName = "(PG) Boonie Hat (Desert MARPAT)";
		picture = "\PG_Services_PMC\icons\icon_H_Booniehat_DMARPAT.paa";
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Headgear\booniehat_dmarpat_co.paa"};
	};
	
	class H_Booniehat_GCAMO : H_Booniehat_khk {
		author = "Pomigit";
		displayName = "(PG) Boonie hat (Woodland Camo)";
		picture = "\PG_Services_PMC\icons\icon_H_Booniehat_GCAMO.paa";
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Headgear\booniehat_gcamo_co.paa"};
	};
};
