// config.bin - 17:23:31 04/24/15, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	 //  = 2,	// Error parsing: Empty enum name
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXESXYZ = 4,
	STABILIZEDINAXISY = 2,
	STABILIZEDINAXESBOTH = 3,
	DESTRUCTNO = 0,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class DefaultEventhandlers;	// External class reference

class CfgPatches {
	class PG_Services_PMC_vehicles {
		units[] = {"PMC_Offroad_Transport", "PMC_Offroad_Armed", "PMC_Offroad_Cargo", PMC_MH9};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {};
		version = 0.1;
	};
};

class UniformSlotInfo {
	slotType = 0;
	linkProxy = "-";
};

class CfgVehicles {
	class B_Heli_Light_01_F;	// External class reference
	class Offroad_01_base_F;	// External class reference
	class Offroad_01_armed_base_F;	// External class reference
	
	class PMC_MH9 : B_Heli_Light_01_F {
		displayName = "MH-9 PMC";
		side = 2;
		faction = "PG_Services";
		author = "Pomigit";
		crew = "PMC_Helipilot";
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\MH9\Heli_light01_ext_pmc_co.paa", "a3\air_f\mh9\data\heli_medium01_detail_co.paa", "\PG_Services_PMC\textures\MH9\heli_light01_int_pmc_co.paa"};
	};
	
	class PMC_Offroad_Transport : Offroad_01_base_F {
		scope = 2;
		side = 2;
		author = "BadHabitz";
		faction = "PG_Services";
		displayName = "(PG) Offroad Transport";
		crew = "PMC_SecurityCon_MX";
		typicalCargo[] = {"PMC_Engineer"};
		enableGPS = 1;
		transportMaxBackpacks = 6;
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Vehicles\offroad_01.paa", "\PG_Services_PMC\textures\Vehicles\offroad_01.paa"};
		
		class Turrets {};
		
		class TransportItems {
			class _xx_ToolKit {
				name = "ToolKit";
				count = 1;
			};
			
			class _xx_Medikit {
				name = "Medikit";
				count = 1;
			};
			
			class _xx_FirstAidKit {
				name = "FirstAidKit";
				count = 10;
			};
		};
	};
	
	class PMC_Offroad_Armed : Offroad_01_armed_base_F {
		scope = 2;
		side = 2;
		author = "BadHabitz";
		faction = "PG_Services";
		displayName = "(PG) Offroad Armed";
		crew = "PMC_SecurityCon_MX";
		typicalCargo[] = {"PMC_Engineer"};
		enableGPS = 1;
		mapSize = 5;
		transportMaxBackpacks = 6;
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Vehicles\offroad_01.paa", "\PG_Services_PMC\textures\Vehicles\offroad_01.paa"};
		
		class TransportItems {
			class _xx_ToolKit {
				name = "ToolKit";
				count = 1;
			};
			
			class _xx_Medikit {
				name = "Medikit";
				count = 1;
			};
			
			class _xx_FirstAidKit {
				name = "FirstAidKit";
				count = 10;
			};
		};
	};
	
	class PMC_Offroad_Cargo : Offroad_01_base_F {
		scope = 2;
		side = 2;
		author = "BadHabitz";
		faction = "PG_Services";
		displayName = "(PG) Offroad Cargo";
		crew = "PMC_SecurityCon_MX";
		typicalCargo[] = {"PMC_Engineer"};
		enableGPS = 1;
		transportSoldier = 1;
		cargoAction[] = {"passenger_low01"};
		transportMaxBackpacks = 6;
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Vehicles\offroad_01.paa", "\PG_Services_PMC\textures\Vehicles\offroad_01.paa"};
		
		class Turrets {};
		
		class TransportItems {
			class _xx_ToolKit {
				name = "ToolKit";
				count = 1;
			};
			
			class _xx_Medikit {
				name = "Medikit";
				count = 1;
			};
			
			class _xx_FirstAidKit {
				name = "FirstAidKit";
				count = 10;
			};
		};
	};
};
