// config.bin - 17:20:02 04/24/15, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXESXYZ = 4,
	STABILIZEDINAXISY = 2,
	STABILIZEDINAXESBOTH = 3,
	DESTRUCTNO = 0,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class DefaultEventhandlers;	// External class reference

class CfgPatches {
	class PG_Services_PMC_Ammoboxes {
		units[] = {"PG_PMC_weaponCrate_F", "PG_PMC_uniformCrate_F", "PG_PMC_gearCrate_F"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"A3_Weapons_F"};
	};
};

class CfgVehicles {
	class Box_NATO_Wps_F;	// External class reference
	class Box_IND_Ammo_F;	// External class reference
	
		class PG_PMC_uniformCrate_F : Box_IND_Ammo_F {
		scope = 2;
		author = "BadHabitz";
		vehicleClass = "Ammo";
		displayName = "(PG) Uniforms Crate";
		icon = "iconobject_1x1";
		model = "\A3\Structures_F_EPA\Mil\Scrapyard\PaperBox_closed_F.p3d";
		
		class TransportMagazines {};
		
		class TransportItems {
			class _xx_U_PMC_GTShirt_DJeans {
				name = "U_PMC_GTShirt_DJeans";
				count = 1;
			};
			
			class _xx_U_PMC_GTShirt_SJeans {
				name = "U_PMC_GTShirt_SJeans";
				count = 1;
			};
			
			class _xx_U_PMC_BlkTShirt_DJeans {
				name = "U_PMC_BlkTShirt_DJeans";
				count = 1;
			};
			
			class _xx_U_PMC_BlkTShirt_SJeans {
				name = "U_PMC_BlkTShirt_SJeans";
				count = 1;
			};
			
			class _xx_U_PMC_BluTShirt_SJeans {
				name = "U_PMC_BluTShirt_SJeans";
				count = 1;
			};
			
			class _xx_U_PMC_WTShirt_DJeans {
				name = "U_PMC_WTShirt_DJeans";
				count = 1;
			};
			
			class _xx_U_PMC_BluePlaidShirt_BeigeCords {
				name = "U_PMC_BluePlaidShirt_BeigeCords";
				count = 1;
			};
			
			class _xx_U_PMC_RedPlaidShirt_DenimCords {
				name = "U_PMC_RedPlaidShirt_DenimCords";
				count = 1;
			};
			
			class _xx_U_PMC_BlackPoloShirt_BeigeCords {
				name = "U_PMC_BlackPoloShirt_BeigeCords";
				count = 1;
			};
			
			class _xx_U_PMC_BluPolo_BgPants {
				name = "U_PMC_BluPolo_BgPants";
				count = 1;
			};
			
			class _xx_U_PMC_BgPolo_GrnPants {
				name = "U_PMC_BgPolo_GrnPants";
				count = 1;
			};
			
			class _xx_U_PMC_BlckPolo_BgPants {
				name = "U_PMC_BlckPolo_BgPants";
				count = 1;
			};
			
			class _xx_U_PMC_BlckPolo_BluPants {
				name = "U_PMC_BlckPolo_BluPants";
				count = 1;
			};
			
			class _xx_U_PMC_BluPolo_GrnPants {
				name = "U_PMC_BluPolo_GrnPants";
				count = 1;
			};
			
			class _xx_U_PMC_BrnPolo_BgPants {
				name = "U_PMC_BrnPolo_BgPants";
				count = 1;
			};
			
			class _xx_U_PMC_BrnPolo_BluPants {
				name = "U_PMC_BrnPolo_BluPants";
				count = 1;
			};
			
			class _xx_U_PMC_GrnPolo_BgPants {
				name = "U_PMC_GrnPolo_BgPants";
				count = 1;
			};
			
			class _xx_U_PMC_WhtPolo_BgPants {
				name = "U_PMC_WhtPolo_BgPants";
				count = 1;
			};
			
			class _xx_U_PMC_WhtPolo_BluPants {
				name = "U_PMC_WhtPolo_BluPants";
				count = 1;
			};
			
			class _xx_U_PMC_WhtPolo_GrnPants {
				name = "U_PMC_WhtPolo_GrnPants";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformRS_BSGPBB {
				name = "U_PMC_CombatUniformRS_BSGPBB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformRS_BSGPSB {
				name = "U_PMC_CombatUniformRS_BSGPSB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformRS_BSSPBB {
				name = "U_PMC_CombatUniformRS_BSSPBB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformRS_BSSPSB {
				name = "U_PMC_CombatUniformRS_BSSPSB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformRS_GSBPBB {
				name = "U_PMC_CombatUniformRS_GSBPBB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformRS_GSSPBB {
				name = "U_PMC_CombatUniformRS_GSSPBB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformRS_IndPBSBB {
				name = "U_PMC_CombatUniformRS_IndPBSBB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformRS_SSBPBB {
				name = "U_PMC_CombatUniformRS_SSBPBB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformRS_SSGPBB {
				name = "U_PMC_CombatUniformRS_SSGPBB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformRS_SSGPSB {
				name = "U_PMC_CombatUniformRS_SSGPSB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformRS_ChckDBS_GPSB {
				name = "U_PMC_CombatUniformRS_ChckDBS_GPSB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformRS_ChckLB_GPBB {
				name = "U_PMC_CombatUniformRS_ChckLB_GPBB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformRS_ChckLR_SPBB {
				name = "U_PMC_CombatUniformRS_ChckLR_SPBB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformRS_ChckP_BPBB {
				name = "U_PMC_CombatUniformRS_ChckP_BPBB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformLS_BSGPBB {
				name = "U_PMC_CombatUniformLS_BSGPBB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformLS_BSGPSB {
				name = "U_PMC_CombatUniformLS_BSGPSB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformLS_BSSPBB {
				name = "U_PMC_CombatUniformLS_BSSPBB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformLS_BSSPSB {
				name = "U_PMC_CombatUniformLS_BSSPSB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformLS_GSBPBB {
				name = "U_PMC_CombatUniformLS_GSBPBB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformLS_GSSPBB {
				name = "U_PMC_CombatUniformLS_GSSPBB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformLS_IndPBSBB {
				name = "U_PMC_CombatUniformLS_IndPBSBB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformLS_SSBPBB {
				name = "U_PMC_CombatUniformLS_SSBPBB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformLS_SSGPBB {
				name = "U_PMC_CombatUniformLS_SSGPBB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformLS_SSGPSB {
				name = "U_PMC_CombatUniformLS_SSGPSB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformLS_ChckDBS_GPSB {
				name = "U_PMC_CombatUniformLS_ChckDBS_GPSB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformLS_ChckLB_GPBB {
				name = "U_PMC_CombatUniformLS_ChckLB_GPBB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformLS_ChckLR_SPBB {
				name = "U_PMC_CombatUniformLS_ChckLR_SPBB";
				count = 1;
			};
			
			class _xx_U_PMC_CombatUniformLS_ChckP_BPBB {
				name = "U_PMC_CombatUniformLS_ChckP_BPBB";
				count = 1;
			};
		};
		
		class TransportWeapons {};
		
		class TransportBackpacks {};
	};
	
	class PG_PMC_gearCrate_F : Box_IND_Ammo_F {
		scope = 2;
		author = "BadHabitz";
		vehicleClass = "Ammo";
		displayName = "(PG) Vests and Headgear Crate";
		icon = "iconobject_1x1";
		model = "\A3\Structures_F_EPA\Mil\Scrapyard\Paperbox_closed_F.p3d";
		
		class TransportMagazines {};
		
		class TransportItems {
			class _xx_H_Cap_pmc {
				name = "H_Cap_pmc";
				count = 2;
			};
			
			class _xx_H_Cap_tan_pmc {
				name = "H_Cap_tan_pmc";
				count = 2;
			};
			
			class _xx_H_Cap_pmc_headphones {
				name = "H_Cap_pmc_headphones";
				count = 2;
			};
			
			class _xx_H_Capbw_pmc {
				name = "H_Capbw_pmc";
				count = 2;
			};
			
			class _xx_H_Capbw_tan_pmc {
				name = "H_Capbw_tan_pmc";
				count = 2;
			};
			
			class _xx_H_Booniehat_rgr {
				name = "H_Booniehat_rgr";
				count = 2;
			};
			
			class _xx_H_Booniehat_GCAMO {
				name = "H_Booniehat_GCAMO";
				count = 2;
			};
			
			class _xx_H_Booniehat_DMARPAT {
				name = "H_Booniehat_DMARPAT";
				count = 2;
			};
			
			class _xx_H_HelmetB_plain_blk {
				name = "H_HelmetB_plain_blk";
				count = 2;
			};
			
			class _xx_H_PilotHelmetHeli_PMC {
				name = "H_PilotHelmetHeli_PMC";
				count = 2;
			};
			
			class _xx_V_PlateCarrierInd_PMC_blk {
				name = "V_PlateCarrierInd_PMC_blk";
				count = 2;
			};
			
			class _xx_V_PlateCarrierInd_PMC_grn {
				name = "V_PlateCarrierInd_PMC_grn";
				count = 2;
			};
			
			class _xx_V_TacVest_darkblck {
				name = "V_TacVest_darkblck";
				count = 2;
			};
			
			class _xx_V_PlateCarrier1_PMC_khki {
				name = "V_PlateCarrier1_PMC_khki";
				count = 2;
			};
			
			class _xx_V_PlateCarrier1_PMC_marpat {
				name = "V_PlateCarrier1_PMC_marpat";
				count = 2;
			};
			
			class _xx_V_PlateCarrier1_PMC_rgr {
				name = "V_PlateCarrier1_PMC_rgr";
				count = 2;
			};
			
			class _xx_V_PlateCarrier1_PMC_blk {
				name = "V_PlateCarrier1_PMC_blk";
				count = 2;
			};
			
			class _xx_pmc_earpiece {
				name = "pmc_earpiece";
				count = 2;
			};
			
			class _xx_Pomi_Goggles {
				name = "Pomi_Goggles";
				count = 2;
			};
			
			class _xx_Pomi_Goggles_Grn {
				name = "Pomi_Goggles_Grn";
				count = 2;
			};
			
			class _xx_Pomi_Goggles_Snd {
				name = "Pomi_Goggles_Snd";
				count = 2;
			};
			
			class _xx_NVGoggles_OPFOR {
				name = "Item_NVGoggles_OPFOR";
				count = 10;
			};
			
			class _xx_ItemWatch {
				name = "ItemWatch";
				count = 10;
			};
			
			class _xx_ItemCompass {
				name = "ItemCompass";
				count = 10;
			};
			
			class _xx_ItemGPS {
				name = "ItemGPS";
				count = 10;
			};
			
			class _xx_ItemRadio {
				name = "ItemRadio";
				count = 10;
			};
			
			class _xx_ItemMap {
				name = "ItemMap";
				count = 10;
			};
		};
		
		class TransportWeapons {};
		
		class TransportBackpacks {
			class _xx_B_Kitbag_blk {
				backpack = "B_Kitbag_blk";
				count = 2;
			};
		};
	};
};
