// config.bin - 17:23:00 04/24/15, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	 //  = 2,	// Error parsing: Empty enum name
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXESXYZ = 4,
	STABILIZEDINAXISY = 2,
	STABILIZEDINAXESBOTH = 3,
	DESTRUCTNO = 0,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class DefaultEventhandlers;	// External class reference

class CfgPatches {
	class PG_SERVICES_PMC_UNDERWEAR {
		units[] = {"U_PMC_RGR_BasicBody", "U_PMC_blk_BasicBody", "U_PMC_wht_BasicBody", "U_PMC_blu_BasicBody"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {};
		version = 0.1;
	};
};

class UniformSlotInfo {
	slotType = 0;
	linkProxy = "-";
};

class cfgWeapons {
	class Uniform_Base;	// External class reference
	class UniformItem;	// External class reference
	
	class U_PMC_RGR_BasicBody : Uniform_Base {
		scope = 1;
		displayName = "U_PMC1_BasicBody";
		picture = "\A3\characters_f\data\ui\icon_U_BasicBody_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_soldier";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Underwear_PMC_RGR";
			containerClass = "Supply0";
			mass = 1;
		};
	};
	
	class U_PMC_blk_BasicBody : Uniform_Base {
		scope = 1;
		displayName = "U_PMC2_BasicBody";
		picture = "\A3\characters_f\data\ui\icon_U_BasicBody_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_soldier";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Underwear_PMC_BLK";
			containerClass = "Supply0";
			mass = 1;
		};
	};
	
	class U_PMC_wht_BasicBody : Uniform_Base {
		scope = 1;
		displayName = "U_PMC3_BasicBody";
		picture = "\A3\characters_f\data\ui\icon_U_BasicBody_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_soldier";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Underwear_PMC_WHT";
			containerClass = "Supply0";
			mass = 1;
		};
	};
	
	class U_PMC_blu_BasicBody : Uniform_Base {
		scope = 1;
		displayName = "U_PMC4_BasicBody";
		picture = "\A3\characters_f\data\ui\icon_U_BasicBody_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_soldier";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Underwear_PMC_BLU";
			containerClass = "Supply0";
			mass = 1;
		};
	};
};
