// config.bin - 17:20:41 04/24/15, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	 //  = 2,	// Error parsing: Empty enum name
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXESXYZ = 4,
	STABILIZEDINAXISY = 2,
	STABILIZEDINAXESBOTH = 3,
	DESTRUCTNO = 0,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class PG_Services_PMC_CLIENT {
		units[] = {PMC_VIP_F};
		weapons[] = {"vip_clothes"};
		requiredVersion = 0.1;
		requiredAddons[] = {};
	};
};

class cfgWeapons {
	class ItemCore;	// External class reference
	class InventoryItem_Base_F;	// External class reference
	class UniformItem;	// External class reference
	class Uniform_Base;	// External class reference
	
	class vip_clothes : Uniform_Base {
		scope = 1;
		displayName = "Civilian Clothes";
		picture = "\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = PMC_VIP_F;
			containerClass = "Supply10";
			mass = 60;
		};
	};
};

class CfgVehicles {
	class Civilian_F;	// External class reference
	
	class PMC_VIP_F : Civilian_F {
		scope = 2;
		author = "Pomigit";
		side = 2;
		faction = "PG_Services";
		vehicleClass = "MenStory";
		model = "\PG_Services_PMC\client\client";
		displayName = "VIP Client";
		uniformClass = "vip_clothes";
		linkeditems[] = {"G_Squares_Tinted"};
		respawnlinkeditems[] = {"G_Squares_Tinted"};
	};
};
