// config.bin - 17:20:21 04/24/15, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	 //  = 2,	// Error parsing: Empty enum name
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXESXYZ = 4,
	STABILIZEDINAXISY = 2,
	STABILIZEDINAXESBOTH = 3,
	DESTRUCTNO = 0,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class DefaultEventhandlers;	// External class reference

class CfgPatches {
	class PG_Services_PMC_Bags {
		units[] = {"B_Bergen_rgr_Exp", "B_Kitbag_blk_Medic", "PMC_B_Kitbag_blk", "PMC_B_Carryall_blk", "PMC_AssaultPack_Tan", "PMC_AssaultPack_Blk", "PMC_AssaultPack_Rgr"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {};
		version = 0.1;
	};
};

class CfgVehicles {
	class B_Bergen_rgr;	// External class reference
	class B_Kitbag_Base;	// External class reference
	class B_Carryall_Base;	// External class reference
	class B_AssaultPack_Kerry;	// External class reference
	
	class B_Bergen_rgr_Exp : B_Bergen_rgr {
		scope = 1;
		author = "Pomigit";
		displayName = "Technician Bag";
		
		class TransportMagazines {
			class _xx_APERSBoundingMine_Range_Mag {
				magazine = "APERSBoundingMine_Range_Mag";
				count = 3;
			};
			
			class _xx_ClaymoreDirectionalMine_Remote_Mag {
				magazine = "ClaymoreDirectionalMine_Remote_Mag";
				count = 2;
			};
			
			class _xx_SLAMDirectionalMine_Wire_Mag {
				magazine = "SLAMDirectionalMine_Wire_Mag";
				count = 2;
			};
			
			class _xx_DemoCharge_Remote_Mag {
				magazine = "DemoCharge_Remote_Mag";
				count = 1;
			};
		};
		
		class TransportItems {
			class _xx_ToolKit {
				name = "ToolKit";
				count = 1;
			};
			
			class _xx_MineDetector {
				name = "MineDetector";
				count = 1;
			};
		};
	};
	
	class PMC_B_Kitbag_blk : B_Kitbag_Base {
		scope = 2;
		author = "BadHabitz";
		picture = "\PG_Services_PMC\icons\icon_B_PMC_fast_blk.paa";
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack_fast_blk_co.paa"};
		displayName = "(PG) Kitbag (Black)";
	};
	
	class PMC_B_Carryall_blk : B_Carryall_Base {
		scope = 2;
		author = "BadHabitz";
		picture = "\A3\Weapons_F\Ammoboxes\Bags\data\UI\icon_B_C_Tortila_blk.paa";
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack_tortila_blk_co.paa"};
		displayName = "(PG) Carryall (Black)";
	};
	
	class PMC_AssaultPack_Tan : B_AssaultPack_Kerry {
		scope = 2;
		author = "BadHabitz";
		displayName = "(PG) Assault Pack (tan)";
		picture = "\PG_Services_PMC\icons\icon_B_PMC_compact_tan.paa";
		hiddenselections[] = {"camo1", "camo2"};
		hiddenSelectionsTextures[] = {"\PG_Services_PMC\textures\Backpacks\assaultpack_PG_tan_co.paa", "\PG_Services_PMC\textures\vests\vests_PG_tan_co.paa"};
		model = "\A3\Characters_F_EPA\Blufor\backpack_kerry";
		maximumLoad = 120;
	};
	
	class PMC_AssaultPack_Blk : B_AssaultPack_Kerry {
		scope = 2;
		author = "BadHabitz";
		displayName = "(PG) Assault Pack (black)";
		picture = "\A3\Weapons_F\Ammoboxes\Bags\data\UI\icon_B_C_Compact_blk_ca.paa";
		hiddenselections[] = {"camo1", "camo2"};
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack_compact_blk_co.paa", "\PG_Services_PMC\textures\vests\vests_PG_blk_co.paa"};
		model = "\A3\Characters_F_EPA\Blufor\backpack_kerry";
		maximumLoad = 120;
	};
	
	class PMC_AssaultPack_Rgr : B_AssaultPack_Kerry {
		scope = 2;
		author = "BadHabitz";
		displayName = "(PG) Assault Pack (green)";
		picture = "\A3\Weapons_F\Ammoboxes\Bags\data\UI\icon_B_C_Compact_rgr_ca.paa";
		hiddenselections[] = {"camo1", "camo2"};
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack_compact_rgr_co.paa", "\PG_Services_PMC\textures\vests\vests_PG_rgr_co.paa"};
		model = "\A3\Characters_F_EPA\Blufor\backpack_kerry";
		maximumLoad = 120;
	};
	
	class B_Kitbag_blk_Medic : PMC_B_Kitbag_blk {
		scope = 1;
		author = "Pomigit";
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack_fast_blk_co.paa"};
		displayName = "Medic Bag";
		
		class TransportItems {
			class _xx_Medikit {
				name = "Medikit";
				count = 1;
			};
			
			class _xx_FirstAidKit {
				name = "FirstAidKit";
				count = 10;
			};
		};
	};
};
