// config.bin - 15:34:53 02/23/15, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class hmg_weapons {
		requiredaddons[] = {"A3_Data_F", "hlcweapons_aks", "rhs_c_weapons", "A3_Anims_F", "A3_Anims_F_Config_Sdr", "A3_Weapons_F", "asdg_jointrails", "hlcweapons_core"};
		weapons[] = {"hmg_rpk74"};
		units[] = {};
	};
};
class Mode_SemiAuto;	// External class reference
class Mode_FullAuto;	// External class reference
class SlotInfo;	// External class reference
class CowsSlot;	// External class reference
class PointerSlot;	// External class reference

class CfgWeapons {
	class Rifle;	// External class reference
	class WeaponSlotsInfo;	// External class reference
	class hlc_rifle_rpk;	// External class reference
	class hmg_rpk74 : hlc_rifle_rpk {
		inertia = 0.6;
		author = "Wieking";
		reloadAction = "HLC_GestureReloadRPK";
		scope = 2;
		aidispersioncoefx = 10;
		aidispersioncoefy = 12;
		AB_barrelTwist = 7.78;
		AB_barrelLength = 23.2;
		agm_bipod = 1;
		cse_bipod = 1;
		bg_bipod = 1;
		magazines[] = {"rhs_45Rnd_545x39_AK", "rhs_45Rnd_545x39_7N10_AK", "rhs_45Rnd_545x39_7N22_AK", "rhs_45Rnd_545x39_AK_green", "rhs_30Rnd_545x39_AK", "rhs_30Rnd_545x39_7N10_AK", "rhs_30Rnd_545x39_7N22_AK", "rhs_30Rnd_545x39_AK_green"};
		model = "\hlc_wp_ak\mesh\rpk\rpk.p3d";
		picture = "\hlc_wp_ak\tex\ui\gear_rpk_x_ca";
		UiPicture = "\A3\weapons_f\data\UI\icon_regular_CA.paa";
		displayName = "RPK74";
		discreteDistance[] = {440, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000};
		discretedistanceinitindex = 0;
		descriptionShort = "Light Support Weapon<br/>Caliber: 5.45mm";
		drysound[] = {"\hlc_core\sound\empty_assaultrifles", 1, 1, 10};
		opticszoominit = 0.75;
		opticszoommax = 1.1;
		opticszoommin = 0.375;
		reloadMagazineSound[] = {"\hlc_wp_ak\snd\rpk_reload_me", 0.74, 1, 30};
		modes[] = {"FullAuto", "Single", "fullauto_medium", "single_medium_optics1", "single_far_optics2", "medium", "close"};
		
		class FullAuto : Mode_FullAuto {
			reloadTime = 0.1;
			recoil = "recoil_auto_mx";
			recoilProne = "recoil_auto_prone_mx";
			sounds[] = {"StandardSound", "SilencedSound"};
			
			class BaseSoundModeType {
				weaponSoundEffect = "DefaultRifle";
				closure1[] = {"\hlc_wp_ak\snd\ak74_first", 1, 1, 10};
				closure2[] = {"\hlc_wp_ak\snd\ak74_first", 1, 1, 10};
				soundClosure[] = {"closure1", 0.5, "closure2", 0.5};
			};
			
			class StandardSound : BaseSoundModeType {
				begin1[] = {"\hlc_wp_ak\snd\rpk_fire", 1, 1, 1200};
				begin2[] = {"\hlc_wp_ak\snd\rpk_fire", 1, 1, 1200};
				begin3[] = {"\hlc_wp_ak\snd\rpk_fire", 1, 1, 1200};
				soundBegin[] = {"begin1", 0.33, "begin2", 0.33, "begin3", 0.34};
			};
			
			class SilencedSound : BaseSoundModeType {
				begin1[] = {"\hlc_wp_ak\snd\rpk_sil", 1, 1, 200};
				begin2[] = {"\hlc_wp_ak\snd\rpk_sil", 1, 1, 200};
				soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			};
		};
		
		class Single : Mode_SemiAuto {
			reloadTime = 0.1;
			soundClosure[] = {"closure1", 0.5, "closure2", 0.5};
			recoil = "recoil_single_mx";
			recoilprone = "recoil_single_prone_mx";
			sounds[] = {"StandardSound", "SilencedSound"};
			
			class BaseSoundModeType {
				weaponSoundEffect = "DefaultRifle";
				closure1[] = {"\hlc_wp_ak\snd\ak74_first", 1, 1, 10};
				closure2[] = {"\hlc_wp_ak\snd\ak74_first", 1, 1, 10};
				soundClosure[] = {"closure1", 0.5, "closure2", 0.5};
			};
			
			class StandardSound : BaseSoundModeType {
				begin1[] = {"\hlc_wp_ak\snd\rpk_fire", 1, 1, 1200};
				begin2[] = {"\hlc_wp_ak\snd\rpk_fire", 1, 1, 1200};
				begin3[] = {"\hlc_wp_ak\snd\rpk_fire", 1, 1, 1200};
				soundBegin[] = {"begin1", 0.33, "begin2", 0.33, "begin3", 0.34};
			};
			
			class SilencedSound : BaseSoundModeType {
				begin1[] = {"\hlc_wp_ak\snd\rpk_sil", 1, 1, 200};
				begin2[] = {"\hlc_wp_ak\snd\rpk_sil", 1, 1, 200};
				soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			};
		};
		
		class fullauto_medium : FullAuto {
			showToPlayer = 0;
			burst = 5;
			minRange = 2;
			minRangeProbab = 0.5;
			midRange = 150;
			midRangeProbab = 0.7;
			maxRange = 300;
			maxRangeProbab = 0.05;
			aiRateOfFire = 0.2;
			aiRateOfFireDistance = 200;
		};
		
		class medium : fullauto_medium {
			showToPlayer = 0;
			airateoffire = 0.2;
			airateoffiredistance = 600;
			burst = 3;
			maxrange = 600;
			maxrangeprobab = 0.1;
			midrange = 400;
			midrangeprobab = 0.6;
			minrange = 200;
			minrangeprobab = 0.05;
		};
		
		class close : FullAuto {
			showToPlayer = 0;
			airateoffire = 0.1;
			airateoffiredistance = 50;
			burst = 10;
			maxrange = 50;
			maxrangeprobab = 0.04;
			midrange = 30;
			midrangeprobab = 0.7;
			minrange = 0;
			minrangeprobab = 0.05;
		};
		
		class ItemInfo {
			priority = 1;
			RMBhint = XMC;
			onHoverText = "TODO XMC DSS";
		};
		
		class WeaponSlotsInfo : WeaponSlotsInfo {
			mass = 96;
			
			class MuzzleSlot : SlotInfo {
				linkProxy = "\A3\data_f\proxies\weapon_slots\MUZZLE";
				compatibleItems[] = {};
			};
			
			class PointerSlot : PointerSlot {
				compatibleItems[] = {};
			};
			
			class CowsSlot : CowsSlot {
				compatibleItems[] = {};
			};
		};
	};
};

class cfgMods {
	author = 76561198039855990;
	timepacked = 1424606521;
};
