// config.bin - 17:21:57 04/24/15, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class PG_Services_PMC_Goggles {
		units[] = {"Pomi_Goggles", "Pomi_Goggles_Grn", "Pomi_Goggles_Snd"};
		weapons[] = {"Pomi_Goggles", "Pomi_Goggles_Grn", "Pomi_Goggles_Snd"};
		requiredVersion = 0.1;
		requiredAddons[] = {};
	};
};

class CfgGlasses {
	class G_Tactical_Clear;	// External class reference
	
	class Pomi_Goggles : G_Tactical_Clear {
		displayname = "(PG) Tactical Goggles (Black)";
		model = "\PG_Services_PMC\pomi_goggles";
		picture = "\A3\Characters_F\data\ui\icon_g_tactical_CA.paa";
		identityTypes[] = {"NoGlasses", 0, "G_NATO_default", 250};
	};
	
	class Pomi_Goggles_Grn : Pomi_Goggles {
		displayname = "(PG) Tactical Goggles (Green)";
		model = "\PG_Services_PMC\pomi_goggles_grn";
		picture = "\A3\Characters_F\data\ui\icon_g_tactical_CA.paa";
		identityTypes[] = {"NoGlasses", 0, "G_NATO_default", 250};
	};
	
	class Pomi_Goggles_Snd : Pomi_Goggles {
		displayname = "(PG) Tactical Goggles (Sand)";
		model = "\PG_Services_PMC\pomi_goggles_Snd";
		picture = "\A3\Characters_F\data\ui\icon_g_tactical_CA.paa";
		identityTypes[] = {"NoGlasses", 0, "G_NATO_default", 250};
	};
};
